@startuml To Be
|#LightGray|Система|

|Гость|
start
:Заходит в кофейню;
:Делает заказ;

|Кассир|
:Принимает заказ;
:Вводит заказ в планшет;

|Система|
:Отправляет заказ на планшеты\nБариста и Повара;

fork
  |Бариста|
  if (Бариста на месте?) then (да)
    :Видит заказ;
  else (нет)
    :Получает push-уведомление;
    :Принимает заказ удалённо;
    :Возвращается на рабочее место;
  endif
  :Начинает готовить напиток;
  :Подаёт напиток в зону выдачи;
fork again
  |Повар|
  if (Повар на месте?) then (да)
    :Видит заказ;
  else (нет)
    :Получает push-уведомление;
    :Принимает заказ удалённо;
    :Возвращается на рабочее место;
  endif
  :Начинает готовить блюдо;
  :Завершает приготовление;
  :Передаёт блюдо в зону выдачи;
end fork

|Бариста|
:Забирает напиток и блюдо\nиз зоны выдачи;
:Относит заказ гостю;

|Гость|
:Получает заказ;
:Наслаждается едой;
:Уходит довольным;
:Пишет положительный отзыв;
stop
@enduml